In [151]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as p
#from array import *
import random
import sympy as sy


In [2]:
#q1-1
x=1
a=0.01
def fun(x):
    return x**2
def d_fun(x):
    return 2*x
for i in range(1,10000):
    x=x-a*d_fun(x)
print(x)

1.8600766854263126e-88


In [10]:
#q1-2

a=0.1
theta = 10000*np.random.rand(2,1)
print(theta)
for i in range(1000):
    theta = theta - a*(2*theta)
print(theta)

[[1232.20729997]
 [ 653.23988969]]
[[1.51590076e-94]
 [8.03636565e-95]]


In [14]:
#q1-3
x=1
a=0.1
def fun(x):
    return 2*(x-1)**2
def d_fun(x):
    return 2*(x-1)
for i in range(1,10000):
    x=x-a*d_fun(x)
print(x)

1.0


In [15]:
#q1-4

a=0.01
theta = np.random.rand(2,1)
for i in range(1000):
    theta = theta - a*(2*(theta-1))
print(theta)

[[1.]
 [1.]]


In [70]:
#q1-e
d=ps.read_excel('data for problem1.xlsx')
mx=(d.x-np.mean(d.x))/np.std(d.x)
my=d.y


#t1=1
#t2=1
#a=0.1
#for i in range(0,100):
    #y=0
   # for i in range(0,93):
    #    y=y+my[i]-t1-t2*mx[i]
        
   # y=-y/94
    
  #  yy=0
 #   for i in range(0,93):
    #    yy=yy+mx[i]*(my[i]-t1-t2*mx[i])
   # yy=-yy/94
    
  #  t1=t1-a*y
 #   t2=t2-a*yy
#print(t1)
#print(t2)


e = np.ones((mx.shape[0],1))
mx2= np.column_stack((e, mx))
my=my.values
my = my.reshape((94, 1))
#print(mx2)
#print(my.shape)

x= np.random.rand(2,1)
m = mx2.shape[0]
a=0.01

for i in range(10000):
    x1 = my - np.matmul(mx2,x)
    x2 = np.matmul(mx2.transpose(),x1)
    x = x + (a)*x2
print(x)

[[23.71808511]
 [-6.86699545]]


In [94]:
#q2
import random as r
d=ps.read_excel('data for problem1.xlsx')
mx=(d.x-np.mean(d.x))/np.std(d.x)
my=d.y
mx
t1=0.5
t2=0.5
a=0.1
for i in range(0,100):
    k=r.randrange(0,93,1)
    y=my[k]-t1-t2*mx[k]
    yy=mx[k]*(my[k]-t1-t2*mx[k])
    t1=t1+a*y
    t2=t2+a*yy
print(t1)
print(t2)

22.461993028803644
-7.428412162244469


In [133]:
#q3-1
from array import *
def j1(a,x):
    return -4*(1 - 2*a)*x*x
def j2(a,x):
    return 8*x*x


x=1
x0=x
e=10
a = 1;
ev = array('f');
while abs(e) > 0.0001 : 
    xx = x;
    x = x - a *(2*x)
    e = xx-x
    ev.append(abs(e))
    a=a-j1(a,x0)/j2(a,x0)
print(x);
#p.plot(ev);
#p.xlabel('Iterations');
#p.ylabel('Error');
#p.title('Errors');

0.0


In [137]:
#q3-2
def j1(a,x):
    return -4*(1 - 2*a)*x*x
def j2(a,x):
    return 8*x*x


x=np.random.rand(2,1)
x0=x
e=10
a = 1;
#print(x0,x0*x0)
while abs(e) > 0.0001 : 
    xx = x;
    x = x - a *(2*x)
    e = abs(xx[0]-x[0])+abs(xx[1]-x[1])
    e=e/2
    a=a-j1(a,x0)/j2(a,x0)
print(x);

[[0.]
 [0.]]


In [146]:
#q3-3
def j1(a,x):
    return 8*a*(x-1)*(x-1)-4*x*(x-1)+4*(x-1)
def j2(a,x):
    return 8*(x-1)*(x-1)


x=10
x0=x
e=1
a = 100;
ev = array('f');
i=0
while abs(e) > 0.0001 : 
    xx = x;
    x = x - a *(2*(x-1))
    e = xx-x
    i=i+1
    ev.append(abs(e))
    a=a-j1(a,x0)/j2(a,x0)
print(x);
#p.plot(ev);
#p.xlabel('Iterations');
#p.ylabel('Error');
#p.title('Errors');
print(i)

1.0
3


In [147]:
#q3-4
def j1(a,x):
    return 8*a*(x-1)*(x-1)-4*x*(x-1)+4*(x-1)
def j2(a,x):
    return 8*(x-1)*(x-1)


x=np.random.rand(2,1)
x0=x
e=10
a = 1;
i=0;
while abs(e) > 0.0001 : 
    xx = x;
    x = x - a *(2*(x-1))
    e = abs(xx[0]-x[0])+abs(xx[1]-x[1])
    e=e/2
    a=a-j1(a,x0)/j2(a,x0)
    i=i+1
print(x);
print(i)

[[1.]
 [1.]]
3


In [5]:
#3-5
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as pl
from mpl_toolkits import mplot3d
import statistics as st
import sympy as sy

data=pd.read_excel('data for problem1.xlsx')
x=np.array(data['x'])
y=np.array(data['y'])
x=(x-np.mean(x))/np.std(x)
o0=10
o1=10

t0=sy.Symbol('t0');
t1=sy.Symbol('t1');

eq=sy.simplify(sum([(y[i]-(t0+t1*x[i]))**2 for i in range(len(x))]))
#print(eq)
part0=sy.diff(eq,t0)
part1=sy.diff(eq,t1)
part00=sy.lambdify([t0,t1],part0,'numpy')
part11=sy.lambdify([t0,t1],part1,'numpy')
print(part0)
#print(part00)

a=sy.Symbol('a')
eq1=sy.simplify(sum([(y[i]-(t0-a*part0+(t1-a*part1)*x[i]))**2 for i in range(len(x))]))
diff1=sy.diff(eq1,a);
diff2=sy.diff(diff1,a);
diff1=sy.lambdify([a,t0,t1],diff1,'numpy')
diff2=sy.lambdify([a,t0,t1],diff2,'numpy')
prev0=o0+1
prev1=o1+1

eps=1e-10
alpha=0.1
ni=0
while(abs(o0-prev0)>=eps or abs(o1-prev1)>=eps ):
    prev0=o0
    prev1=o1
    alpha=alpha-diff1(alpha,10,10)/diff2(alpha,10,10)
    o0=o0-alpha*part00(prev0,prev1)
    o1=o1-alpha*part11(prev0,prev1)
    ni=ni+1
print(o0,o1,ni)

188.0*t0 - 1.31561428418081e-14*t1 - 4459.0
23.718085106382983 -6.866995447255372 2


In [92]:
#practis q1
def value(x,y,t,x2):
    m=np.random.rand(2,1)
    m[0]=np.sum(y-(x*t))
    m[1]=np.sum(np.multiply(y-x*t,x2))
    return m

d=pd.read_excel("data for Problem1.xlsx")
x=d['x']
y=d['y']
y=np.matrix(y).T
x=(x-np.mean(x))/np.std(x)
x=np.matrix(x).T
x2=x
o=np.matrix(np.ones(len(x))).T
x=np.concatenate((o,x),axis=1)
t=np.random.rand(2,1)
a=0.001


for i in range(10000):
    t=t+(a)*value(x,y,t,x2)

print(t)

[[23.71808511]
 [-6.86699545]]


In [130]:
#practice q2
def value(x,y,t,x2):
    m=np.random.rand(2,1)
    k=random.randrange(len(y))
    m[0]=y[k]-(x[k]*t)
    m[1]=(y[k]-x[k]*t)*x2[k]
    return m

d=pd.read_excel("data for Problem1.xlsx")
x=d['x']
y=d['y']
y=np.matrix(y).T
x=(x-np.mean(x))/np.std(x)
x=np.matrix(x).T
x2=x
o=np.matrix(np.ones(len(x))).T
x=np.concatenate((o,x),axis=1)
t=np.random.rand(2,1)
a=0.001


for i in range(10000):
    t=t+(a)*value(x,y,t,x2)

print(t)

[[23.73350866]
 [-6.83886397]]


[[0]]
