In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [13]:
df = pd.read_csv("mnist_train.csv")
df.sort_values(by=['label'],ascending=True,inplace=True)
x_train = df.iloc[:,0:785]
print(x_train.shape)
df

       label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...    1x775  \
30207      0    0    0    0    0    0    0    0    0    0  ...        0   
5662       0    0    0    0    0    0    0    0    0    0  ...        0   
55366      0    0    0    0    0    0    0    0    0    0  ...        0   
14160      0    0    0    0    0    0    0    0    0    0  ...        0   
14161      0    0    0    0    0    0    0    0    0    0  ...        0   
14165      0    0    0    0    0    0    0    0    0    0  ...        0   
24693      0    0    0    0    0    0    0    0    0    0  ...        0   
24689      0    0    0    0    0    0    0    0    0    0  ...        0   
29676      0    0    0    0    0    0    0    0    0    0  ...        0   
29677      0    0    0    0    0    0    0    0    0    0  ...        0   
14179      0    0    0    0    0    0    0    0    0    0  ...        0   
5646       0    0    0    0    0    0    0    0    0    0  ...        0   
55361      0    0    0   

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...    1x775  \
30207      0    0    0    0    0    0    0    0    0    0  ...        0   
5662       0    0    0    0    0    0    0    0    0    0  ...        0   
55366      0    0    0    0    0    0    0    0    0    0  ...        0   
14160      0    0    0    0    0    0    0    0    0    0  ...        0   
14161      0    0    0    0    0    0    0    0    0    0  ...        0   
14165      0    0    0    0    0    0    0    0    0    0  ...        0   
24693      0    0    0    0    0    0    0    0    0    0  ...        0   
24689      0    0    0    0    0    0    0    0    0    0  ...        0   
29676      0    0    0    0    0    0    0    0    0    0  ...        0   
29677      0    0    0    0    0    0    0    0    0    0  ...        0   
14179      0    0    0    0    0    0    0    0    0    0  ...        0   
5646       0    0    0    0    0    0    0    0    0    0  ...        0   
55361      0    0    0    0    0    0    0    0    0    0  ...        0   
48459      0    0    0    0    0    0    0    0    0    0  ...        0   
24681      0    0    0    0    0    0    0    0    0    0  ...        0   
29684      0    0    0    0    0    0    0    0    0    0  ...        0   
24676      0    0    0    0    0    0    0    0    0    0  ...        0   
39935      0    0    0    0    0    0    0    0    0    0  ...        0   
14202      0    0    0    0    0    0    0    0    0    0  ...        0   
29695      0    0    0    0    0    0    0    0    0    0  ...        0   
5627       0    0    0    0    0    0    0    0    0    0  ...        0   
48439      0    0    0    0    0    0    0    0    0    0  ...        0   
48438      0    0    0    0    0    0    0    0    0    0  ...        0   
5622       0    0    0    0    0    0    0    0    0    0  ...        0   
48434      0    0    0    0    0    0    0    0    0    0  ...        0   
5641       0    0    0    0    0    0    0    0    0    0  ...        0   
14158      0    0    0    0    0    0    0    0    0    0  ...        0   
5665       0    0    0    0    0    0    0    0    0    0  ...        0   
14157      0    0    0    0    0    0    0    0    0    0  ...        0   
48511      0    0    0    0    0    0    0    0    0    0  ...        0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...      ...   
9817       9    0    0    0    0    0    0    0    0    0  ...        0   
5544       9    0    0    0    0    0    0    0    0    0  ...        0   
9827       9    0    0    0    0    0    0    0    0    0  ...        0   
41058      9    0    0    0    0    0    0    0    0    0  ...        0   
5518       9    0    0    0    0    0    0    0    0    0  ...        0   
15741      9    0    0    0    0    0    0    0    0    0  ...        0   
23349      9    0    0    0    0    0    0    0    0    0  ...        0   
41014      9    0    0    0    0    0    0    0    0    0  ...        0   
15725      9    0    0    0    0    0    0    0    0    0  ...        0   
9838       9    0    0    0    0    0    0    0    0    0  ...        0   
41021      9    0    0    0    0    0    0    0    0    0  ...        0   
5478       9    0    0    0    0    0    0    0    0    0  ...        0   
23329      9    0    0    0    0    0    0    0    0    0  ...        0   
9835       9    0    0    0    0    0    0    0    0    0  ...        0   
23327      9    0    0    0    0    0    0    0    0    0  ...        0   
5492       9    0    0    0    0    0    0    0    0    0  ...        0   
23463      9    0    0    0    0    0    0    0    0    0  ...        0   
41033      9    0    0    0    0    0    0    0    0    0  ...        0   
52030      9    0    0    0    0    0    0    0    0    0  ...        0   
23314      9    0    0    0    0    0    0    0    0    0  ...        0   
41040      9    0    0    0    0    0    0    0    0    0  ...        0   
41042      9    0    0    0    0

In [15]:
df.sort_values(by=['label'],ascending=True,inplace=True)
x_train = df.iloc[:,1:785]
y_train = df.iloc[:,0]

count = np.zeros([10,1],dtype='int')
for i in range(len(y_train)):
    count[int(y_train.iloc[i])]=count[int(y_train.iloc[i])]+1
print(count)    
m = len(count)
datas = df.as_matrix()
x_train = datas[:,1:785]
y_train = datas[:,0]
for i in range(len(y_train)):
    x_train[i,:] = (x_train[i,:]-x_train[i,:].mean())/x_train[i,:].std()
print(count)
mean = np.zeros([10,784],dtype='int64')
k = 0
x = 0                                          
for i in range(m):
    h = x+count[i]
    for j in range(784):
        mean[k][j] =float((float(np.sum(x_train[int(x):int(h),j])))/float(count[i]))
    x = x + count[i]
    k = k + 1
sigma = 0
sigma = np.empty([len(y_train),784],dtype='int')
q=0
for i in range(m):
    for j in range(int(count[i])):
        sigma[int(q)+j,:] = x_train[int(q)+j,:]-mean[i,:]
    q = q + count[i]


[[5923]
 [6742]
 [5958]
 [6131]
 [5842]
 [5421]
 [5918]
 [6265]
 [5851]
 [5949]]


C:\Users\Saumya Shah\Anaconda3\anap\lib\site-packages\ipykernel_launcher.py:10: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  # Remove the CWD from sys.path while we load stuff.


[[5923]
 [6742]
 [5958]
 [6131]
 [5842]
 [5421]
 [5918]
 [6265]
 [5851]
 [5949]]


In [5]:
x = 0
final_sigma = 0
for i in range(m):
    h = x + count[i]
    final_sigma += (np.dot(sigma[int(x):int(h),:].T,sigma[int(x):int(h),:]))/(count[i]-1)
    x = x + count[i]
final_sigma = final_sigma/10
print(final_sigma.shape)
updated_sigma = final_sigma

(784, 784)


In [20]:
import math as mt
dff = pd.read_csv("mnist_test.csv")
x_test = df.iloc[:,1:785]
y_test = df.iloc[:,0]
datass = dff.as_matrix()
x_test = datass[:,1:785]
y_test = datass[:,0]
pred = np.zeros([10,1],dtype='int')
val = np.zeros([1,784],dtype='int')
vall = np.zeros([784,1],dtype='int')
for i in range(10):
    predictor = 0
    maxi = -1
    for j in range(m):
        val = mean[j,:].reshape(1,784)
        sig_inv = np.linalg.pinv(updated_sigma)
        vall = x_test[i,:].reshape(784,1)
        dot1 = np.dot(sig_inv,vall)
        dot2 = np.dot(val,dot1)
        val_t = val.reshape(784,1)
        dot3 = np.dot(sig_inv,val_t)
        dot4 = np.dot(val,dot3)
        fa = dot2 - 0.5*(dot4) + mt.log(count[j]/len(y_train))
        if(fa>=maxi):
            maxi=fa
            predictor=j
    pred[i]=predictor


C:\Users\Saumya Shah\Anaconda3\anap\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """


In [21]:
cnt=0
for i in range(10):
    if(pred[i]==y_test[i]):
        cnt+=1
print(int(cnt)/10)
#print(pred)

0.9


In [19]:
print(x_test.shape)

(9999, 784)


In [23]:
d=pd.read_csv("mnist_train.csv")

0        5
1        0
2        4
3        1
4        9
5        2
6        1
7        3
8        1
9        4
10       3
11       5
12       3
13       6
14       1
15       7
16       2
17       8
18       6
19       9
20       4
21       0
22       9
23       1
24       1
25       2
26       4
27       3
28       2
29       7
        ..
59970    2
59971    2
59972    0
59973    9
59974    2
59975    4
59976    6
59977    7
59978    3
59979    1
59980    3
59981    6
59982    6
59983    2
59984    1
59985    2
59986    6
59987    0
59988    7
59989    8
59990    9
59991    2
59992    9
59993    5
59994    1
59995    8
59996    3
59997    5
59998    6
59999    8
Name: label, Length: 60000, dtype: int64


In [47]:
from sklearn.model_selection import train_test_split
d.sort_values(by='label',ascending=True,inplace=True)
y=d['label']
#print(y)
x=d.iloc[:,1:785]
c=np.zeros((10,1))
for i in range (len(y)):
    c[y[i]]+=1
print(x.shape)
le=len(c)
#x1,x2,y1,y2=train_test_split(x,y,test_size=0.1)

#print(x1.shape,y2.shape)
h=0
l=0
#print(x)
x=np.matrix(x)
for i in range(len(x)):
    x[i,:]=(x[i,:]-x[i,:].mean())/x[i,:].std()

m=np.zeros((10,784))
for i in range (le):
    h=h+c[i]
    for j in range(784):
        m[i][j]=np.sum(x[int(l):int(h),j])/c[i]
    l=c[i]
print(m)

    
    

(60000, 784)


In [56]:
print(m.shape)
h=0
l=0
s=np.zeros((len(x),784))
for i in range(le):
    h=h+c[i]
    for j in range (int(c[i])):
        s[int(l)+j,:]=x[int(l)+j,:]-m[i,:]
    l=l+c[i]

l=0
h=0
ans=np.zeros((784,784))
for i in range (le):
    h=h+c[i]
    ans+=np.matmul(s[int(l):int(h),:].T,s[int(l):int(h),:])
    l=l+c[i]
    
ans=ans/10
print(ans)

(10, 784)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [57]:
d2=pd.read_csv("mnist_test.csv")
d2

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...    0.658  0.659  \
0     2  0    0    0    0    0    0    0    0    0  ...        0      0   
1     1  0    0    0    0    0    0    0    0    0  ...        0      0   
2     0  0    0    0    0    0    0    0    0    0  ...        0      0   
3     4  0    0    0    0    0    0    0    0    0  ...        0      0   
4     1  0    0    0    0    0    0    0    0    0  ...        0      0   
5     4  0    0    0    0    0    0    0    0    0  ...        0      0   
6     9  0    0    0    0    0    0    0    0    0  ...        0      0   
7     5  0    0    0    0    0    0    0    0    0  ...        0      0   
8     9  0    0    0    0    0    0    0    0    0  ...        0      0   
9     0  0    0    0    0    0    0    0    0    0  ...        0      0   
10    6  0    0    0    0    0    0    0    0    0  ...        0      0   
11    9  0    0    0    0    0    0    0    0    0  ...        0      0   
12    0  0    0    0    0    0    0    0    0    0  ...        0      0   
13    1  0    0    0    0    0    0    0    0    0  ...        0      0   
14    5  0    0    0    0    0    0    0    0    0  ...        0      0   
15    9  0    0    0    0    0    0    0    0    0  ...        0      0   
16    7  0    0    0    0    0    0    0    0    0  ...        0      0   
17    3  0    0    0    0    0    0    0    0    0  ...        0      0   
18    4  0    0    0    0    0    0    0    0    0  ...        0      0   
19    9  0    0    0    0    0    0    0    0    0  ...        0      0   
20    6  0    0    0    0    0    0    0    0    0  ...        0      0   
21    6  0    0    0    0    0    0    0    0    0  ...        0      0   
22    5  0    0    0    0    0    0    0    0    0  ...        0      0   
23    4  0    0    0    0    0    0    0    0    0  ...        0      0   
24    0  0    0    0    0    0    0    0    0    0  ...        0      0   
25    7  0    0    0    0    0    0    0    0    0  ...        0      0   
26    4  0    0    0    0    0    0    0    0    0  ...        0      0   
27    0  0    0    0    0    0    0    0    0    0  ...        0      0   
28    1  0    0    0    0    0    0    0    0    0  ...        0      0   
29    3  0    0    0    0    0    0    0    0    0  ...        0      0   
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...      ...    ...   
9969  5  0    0    0    0    0    0    0    0    0  ...        0      0   
9970  2  0    0    0    0    0    0    0    0    0  ...        0      0   
9971  4  0    0    0    0    0    0    0    0    0  ...        0      0   
9972  9  0    0    0    0    0    0    0    0    0  ...        0      0   
9973  4  0    0    0    0    0    0    0    0    0  ...        0      0   
9974  3  0    0    0    0    0    0    0    0    0  ...        0      0   
9975  6  0    0    0    0    0    0    0    0    0  ...        0      0   
9976  4  0    0    0    0    0    0    0    0    0  ...        0      0   
9977  1  0    0    0    0    0    0    0    0    0  ...        0      0   
9978  7  0    0    0    0    0    0    0    0    0  ...        0      0   
9979  2  0    0    0    0    0    0    0    0    0  ...        0      0   
9980  6  0    0    0    0    0    0    0    0    0  ...        0      0   
9981  5  0    0    0    0    0    0    0    0    0  ...        0      0   
9982  0  0    0    0    0    0    0    0    0    0  ...        0      0   
9983  1  0    0    0    0    0    0    0    0    0  ...        0      0   
9984  2  0    0    0    0    0    0    0    0    0  ...        0      0   
9985  3  0    0    0    0    0    0    0    0    0  ...        0      0   
9986  4  0    0    0    0    0    0    0    0    0  ...        0      0   
9987  5  0    0    0    0    0    0    0    0    0  ...        0      0   
9988  6  0    0    0    0    0    0    0    0    0  ...        0      0   
9989  7  0    0    0    0    0    0    0    0    0  ...        0      0   
9990  8  0    0    0    0    0 

In [89]:
x2=d2.iloc[:,1:785]
y2=d2.iloc[:,0]
x2=np.matrix(x2)
aaa=[]
cc_i=np.linalg.pinv(ans)
for i in range(10):
    xi=x2[i,:]
    p=0
    ma=-1000000000000
    for j in range(le):
        mmm=np.matrix(m[j,:])
        kk=(xi*cc_i)*mmm.T - (0.5)*((mmm*cc_i)*mmm.T) + np.log(c[j]/len(y))
        if(kk > ma):
            ma=kk
            p=j
    aaa.append(p)
print(aaa)

[0, 1, 0, 1, 1, 1, 9, 1, 9, 0]


In [83]:
print(y2)

0       2
1       1
2       0
3       4
4       1
5       4
6       9
7       5
8       9
9       0
10      6
11      9
12      0
13      1
14      5
15      9
16      7
17      3
18      4
19      9
20      6
21      6
22      5
23      4
24      0
25      7
26      4
27      0
28      1
29      3
       ..
9969    5
9970    2
9971    4
9972    9
9973    4
9974    3
9975    6
9976    4
9977    1
9978    7
9979    2
9980    6
9981    5
9982    0
9983    1
9984    2
9985    3
9986    4
9987    5
9988    6
9989    7
9990    8
9991    9
9992    0
9993    1
9994    2
9995    3
9996    4
9997    5
9998    6
Name: 7, Length: 9999, dtype: int64
