In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
df = pd.read_csv("mnist_train_binary.csv")
y = df['label']
df

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...    28x19  28x20  \
0        0    0    0    0    0    0    0    0    0    0  ...        0      0   
1        0    0    0    0    0    0    0    0    0    0  ...        0      0   
2        0    0    0    0    0    0    0    0    0    0  ...        0      0   
3        0    0    0    0    0    0    0    0    0    0  ...        0      0   
4        0    0    0    0    0    0    0    0    0    0  ...        0      0   
5        0    0    0    0    0    0    0    0    0    0  ...        0      0   
6        0    0    0    0    0    0    0    0    0    0  ...        0      0   
7        0    0    0    0    0    0    0    0    0    0  ...        0      0   
8        0    0    0    0    0    0    0    0    0    0  ...        0      0   
9        0    0    0    0    0    0    0    0    0    0  ...        0      0   
10       0    0    0    0    0    0    0    0    0    0  ...        0      0   
11       0    0    0    0    0    0    0    0    0    0  ...        0      0   
12       0    0    0    0    0    0    0    0    0    0  ...        0      0   
13       0    0    0    0    0    0    0    0    0    0  ...        0      0   
14       0    0    0    0    0    0    0    0    0    0  ...        0      0   
15       0    0    0    0    0    0    0    0    0    0  ...        0      0   
16       0    0    0    0    0    0    0    0    0    0  ...        0      0   
17       0    0    0    0    0    0    0    0    0    0  ...        0      0   
18       0    0    0    0    0    0    0    0    0    0  ...        0      0   
19       0    0    0    0    0    0    0    0    0    0  ...        0      0   
20       0    0    0    0    0    0    0    0    0    0  ...        0      0   
21       0    0    0    0    0    0    0    0    0    0  ...        0      0   
22       0    0    0    0    0    0    0    0    0    0  ...        0      0   
23       0    0    0    0    0    0    0    0    0    0  ...        0      0   
24       0    0    0    0    0    0    0    0    0    0  ...        0      0   
25       0    0    0    0    0    0    0    0    0    0  ...        0      0   
26       0    0    0    0    0    0    0    0    0    0  ...        0      0   
27       0    0    0    0    0    0    0    0    0    0  ...        0      0   
28       0    0    0    0    0    0    0    0    0    0  ...        0      0   
29       0    0    0    0    0    0    0    0    0    0  ...        0      0   
..     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...      ...    ...   
970      1    0    0    0    0    0    0    0    0    0  ...        0      0   
971      1    0    0    0    0    0    0    0    0    0  ...        0      0   
972      1    0    0    0    0    0    0    0    0    0  ...        0      0   
973      1    0    0    0    0    0    0    0    0    0  ...        0      0   
974      1    0    0    0    0    0    0    0    0    0  ...        0      0   
975      1    0    0    0    0    0    0    0    0    0  ...        0      0   
976      1    0    0    0    0    0    0    0    0    0  ...        0      0   
977      1    0    0    0    0    0    0    0    0    0  ...        0      0   
978      1    0    0    0    0    0    0    0    0    0  ...        0      0   
979      1    0    0    0    0    0    0    0    0    0  ...        0      0   
980      1    0    0    0    0    0    0    0    0    0  ...        0      0   
981      1    0    0    0    0    0    0    0    0    0  ...        0      0   
982      1    0    0    0    0    0    0    0    0    0  ...        0      0   
983      1    0    0    0    0    0    0    0    0    0  ...        0      0   
984      1    0    0    0    0    0    0    0    0    0  ...        0      0   
985      1    0    0    0    0    0    0    0    0    0  ...        0      0   
986      1    0    0    0    0    0    0    0    0    0  ...        0      0   
987      1    0    0    0    0    0    0    0    0    0  ...        0      0   
988  

In [12]:
import math as mt

count = np.zeros([2,1],dtype='int')
for i in range(len(y)):
    count[int(y.iloc[i])]=count[int(y.iloc[i])]+1
    
m = len(count)
print(m)
datas = df.as_matrix()
a = int(count[0])
b = int(count[1])
print(a,b)
xx_train = datas[0:mt.floor(int(count[0])*0.9),1:785]
yy_train = datas[0:mt.floor(int(count[0])*0.9),0]
xxx_train = datas[int(count[0]):mt.floor(int(count[1])*0.9)+int(count[0]),1:785]
yyy_train = datas[int(count[0]):mt.floor(int(count[1])*0.9)+int(count[0]),0]

x_train = np.vstack((xx_train,xxx_train))
y_train = np.hstack((yy_train,yyy_train))
print(yy_train.shape)
print(xx_train.shape)

xx_test = datas[mt.floor((a*0.9)):a,1:785]
yy_test = datas[mt.floor((a*0.9)):a,0]
xxx_test = datas[mt.floor(a+(b*0.9)):a+b,1:785]
yyy_test = datas[mt.floor(a+(b*0.9)):a+b,0]



x_test = np.vstack((xx_test,xxx_test))
y_test = np.hstack((yy_test,yyy_test))


2
500 500
(450,)
(450, 784)


C:\Users\Saumya Shah\Anaconda3\anap\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  if __name__ == '__main__':


In [14]:
for i in range(len(y_train)):
    x_train[i,:] = (x_train[i,:]-x_train[i,:].mean())/x_train[i,:].std()
print(count)

counter = np.zeros([2,1],dtype='int')
for i in range(len(y_train)):
    counter[(y_train[i])]=counter[(y_train[i])]+1
    
print(counter[0],counter[1])
mean = np.zeros([2,784],dtype='int64')
k = 0
x = 0 
i=0
# x=0 creates nd array
for i in range(m):
    h = x+counter[i]
    for j in range(784):
        mean[k][j] =float((float(np.sum(x_train[int(x):int(h),j])))/float(counter[i]))
    x = x + counter[i]
    k = k + 1
sigma = 0
sigma = np.empty([len(y_train),784],dtype='int')
q=0
for i in range(m):
    for j in range(int(counter[i])):
        sigma[int(q)+j,:] = x_train[int(q)+j,:]-mean[i,:]
    q = q + counter[i]


[[500]
 [500]]
[450] [450]


In [19]:
x = 0
final_sigma = np.zeros([784,784],dtype='float')
for i in range(m):
    h = x + counter[i]
    final_sigma += (np.matmul(sigma[int(x):int(h),:].T,sigma[int(x):int(h),:]))/(counter[i]-1)
    print(final_sigma)
    x = x + counter[i]
final_sigma = final_sigma/2
print(final_sigma.shape)
print(sigma.shape)
updated_sigma = final_sigma


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(784, 784)
(900, 784)


In [21]:
import math as mt
pred = np.zeros([len(y_test),1],dtype='int')
val = np.zeros([1,784],dtype='int')
vall = np.zeros([784,1],dtype='int')
for i in range(len(y_test)):
    predictor = 0
    maxi = -1
    for j in range(m):
        val = mean[j,:].reshape(1,784)
        sig_inv = np.linalg.pinv(updated_sigma)
        vall = x_test[i,:].reshape(784,1)
        dot1 = np.dot(sig_inv,vall)
        dot2 = np.dot(val,dot1)
        val_t = val.reshape(784,1)
        dot3 = np.dot(sig_inv,val_t)
        dot4 = np.dot(val,dot3)
        fa = dot2 - 0.5*(dot4) + mt.log(counter[j]/len(y_train))
        if(fa>maxi):
            maxi=fa
            predictor=j
    pred[i]=predictor


In [22]:
cnt=0
for i in range(len(y_test)):
    if(pred[i]==y_test[i]):
        cnt+=1
print(int(cnt)/len(y_test))
#print(pred)

0.99
